export const SessionActionTypes = {
  REQUEST_LOGIN: "session/REQUEST_LOGIN",
  REQUEST_LOGIN_FINISHED: "session/REQUEST_LOGIN_FINISHED",
  SET_COGNITO_USER_OBJ: "session/SET_COGNITO_USER_OBJ",
  SET_USER_TOKENS: "session/SET_USER_TOKENS",
  ACCOUNT_APPROVAL_STATUS: "session/ACCOUNT_APPROVAL_STATUS",
  REQUEST_REFRESH_TOKEN_SILENTLY: "session/REQUEST_REFRESH_TOKEN_SILENTLY",
};
